# Generated by Django 5.2.11 on 2026-02-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Называие компании')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес компании')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон компании')),
                ('email', models.CharField(max_length=100, verbose_name='Email компании')),
                ('description', models.TextField(verbose_name='Описание компании')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Логотип компании')),
                ('working_hours', models.CharField(max_length=100, verbose_name='Время работы компании')),
            ],
            options={
                'verbose_name': 'Информация о компании',
                'verbose_name_plural': 'Информация о компании',
            },
        ),
    ]
